Repository metwork-framework/mfbase, pull requests merged in 2018-11, with the labels that each got.

#16 chore: add dependency scientific@mfext (potentially for postgis)
  Makefile
Labels: Merge Now, Status: Review Needed

#24 build: postgresql is now in scientific@mfext
  Makefile
Labels: Status: Review Needed

#25 build: move integration tests
  integration_tests/0001_test_basic/test_basic.sh
Labels: Merge Now, Status: Pending

#28 fix: add postgresql extensions on plugin database creation
  adm/_plugins.postinstall
  integration_tests/0002_issue21/_test.sh
  integration_tests/0002_issue21/test.sh
Labels: Merge Now, Status: Review Needed

#30 Preuninstall
  adm/Makefile
  adm/_plugins.preuninstall
Labels: Merge Now, Status: Review Needed

#31 fix: drop the plugin database even if a user is connected
  adm/_plugins.preuninstall
Labels: Merge Now, Status: Pending

#35 feat: change default configuration
  config/config.ini
Labels: Status: Review Needed
