Repository metwork-framework/mfbase, pull requests merged in 2019-04, with the labels that each got.

#46 Revert "refactor: drop name key in plugin config.ini"
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
Labels: Merge Now, Status: Review Needed

#47 refactor: drop duplicate name (the name is already given in CLI)
  adm/templates/plugins/default/cookiecutter.json
Labels: Status: Review Needed, backport-to-0.5, backport-to-0.6

#45 [WIP] feat: mfbase depends now on scientific_core@mfext layer
  .drone.yml
  .layerapi2_dependencies
Labels: Merge Now

#51 build: remove python prerequirement files (useless now)
  layers/layer1_python3/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer1_python3/0500_extra_python_packages/prerequirements3.txt
Labels: Merge Now, Status: Revision Needed

#53 feat: add postgresql dump/restore commands for plugins
  adm/Makefile
  adm/plugins.pgdump.sh
  adm/plugins.pgrestore.sh
Labels: Status: Review Needed

#55 fix: the spatial_ref_sys table is not owned by plugin user
  adm/_plugins.postinstall
Labels: Merge Now, Status: Review Needed

#56 fix: better postgresql status during startup (on slow systems)
  adm/_wait_postgresql.py
Labels: Merge Now, Status: Review Needed
