Repository metwork-framework/mfbase, pull requests merged in 2019-06, with the labels that each got.

#73 docs: generate automatically changelogs entries in changelogs.rst file + update MFBASE documentation
  .gitignore
  doc/Makefile
  doc/_images/grafana_home.jpg
  doc/_images/grafana_login.jpg
  doc/_images/grafana_mfdata_dashboard.jpg
  doc/_images/overall_architecture.svg
  doc/changelogs.tmpl
  doc/index.rst
  doc/mfbase_intro.md
  doc/mfbase_monitoring.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#74 docs: update MFBASE documentation + remove unwanted 'todo'
  doc/_images/overall_architecture.svg
  doc/index.rst
  doc/mfbase_intro.md
  doc/mfbase_monitoring.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#76 fix: add missing send_mflog_logs option in configuration
  config/config.ini
Labels: Status: Review Needed, backport-to-0.7

#78 docs: Update MFBASE documentation
  doc/_images/grafana_home.jpg
  doc/_images/grafana_login.jpg
  doc/_images/grafana_mfdata_dashboard.jpg
  doc/mfbase_intro.md
  doc/mfbase_log.md
  doc/mfbase_monitoring.md
Labels: Status: Review Needed

#79 docs: fix typo
  doc/mfbase_quick_start.md
Labels: Status: Review Needed

#80 Experimental
  bootstrap.sh
Labels: Merge Now, Status: Review Needed
