Repository metwork-framework/mfbase, pull requests merged in 2019-05, with the labels that each got.

#59 build: fix build
  config/telegraf.conf.custom
Labels: Merge Now, Status: Review Needed

#60 docs: Update MFBASE documentation
  .gitignore
  doc/conf.py
  doc/index.rst
  doc/mfbase_load_env.md
Labels: Status: Review Needed

#61 feat: don't use plugin dir as plugin names
  adm/_plugins.postinstall
  adm/_plugins.preuninstall
Labels: Status: Review Needed

#66 build: remove python layer
  layers/layer9_default/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
  layers/layer9_python/layer_custom.md
Labels: Merge Now, Status: Review Needed

#67 docs: fix invalid generated images link url
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/_images/metwork_user_privileges.jpg
  doc/_images/plugin_user_privileges.jpg
  doc/conf.py
  doc/mfbase_quick_start.md
Labels: Status: Review Needed

#68 build: gitignore fix
  .gitignore
Labels: Merge Now, Status: Review Needed

#69 build: typo
  doc/mfbase_quick_start.md
Labels: Merge Now

#70 Mfbasefixes
  adm/Makefile
  adm/_create_plugin_database.sh
  adm/_fix_plugin_owner.py
  adm/_plugins.postinstall
  adm/plugins.pgdump.sh
  adm/plugins.pgrestore.sh
  config/telegraf.conf.custom
Labels: Status: Review Needed, backport-to-0.7

#72 feat: use envtpl new option --reduce-multi-blank-lines
  adm/before_start_postgresql
  doc/Makefile
Labels: Merge Now, Status: Review Needed
