Repository metwork-framework/mfbase, pull requests merged in 2020-05, with the labels that each got.

#116 feat: new plugin system
  adm/Makefile
  adm/__make_nginx_conf
  adm/plugins.py
  adm/profile.custom
  adm/templates/plugins/default/{{cookiecutter.name}}/.plugin_format_version
  adm/templates/plugins/default/{{cookiecutter.name}}/.release_ignore
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/crontab
  config/nginx.conf
Labels: Merge Now, Status: Review Needed

#115 feat: remove all references to MFCOM or mfcom, including backward com…
  config/config.ini.custom
  doc/mfbase_nginx_conf.md
Labels: Status: Review Needed

#117 build: typo
  adm/plugins.py
Labels: Merge Now, backport-to-1.0
