Repository metwork-framework/mfbase, pull requests merged in 2024-03, with the labels that each got.

#276 feat: customize max_connections
  adm/mfxxx.init.custom
  config/config.ini.custom
  config/postgresql.conf
Labels: Status: Revision Needed, backport-to-2.2

#278 build: fix previous changes concerning max_connections
  adm/mfxxx.init.custom
  adm/mfxxx.start.custom
Labels: Status: Review Needed, Status: Merge Now, backport-to-2.2

#280 build: add comment
  config/config.ini.custom
Labels: Status: Review Needed, Status: Merge Now, backport-to-2.2

#285 build: fix again
  adm/mfxxx.start.custom
Labels: Status: Merge Now, backport-to-2.2

#288 fix: configuration _use_storage ignored (#262 bis)
  adm/before_start_nginx
Labels: Status: Review Needed, backport-to-2.2

#291 fix: max_connections in postgresql.conf should be configurable (fix) …
  adm/mfxxx.start.custom
Labels: Status: Review Needed, backport-to-2.2
