Repository metwork-framework/mfbase, pull requests merged in 2024-02, with the labels that each got.

#258 fix: .gitignore missing for new mfbase plugins (#257)
  adm/templates/plugins/default/{{cookiecutter.name}}/.gitignore
Labels: Status: Review Needed, backport-to-2.2

#261 feat: handle autoindex format
  adm/plugins.py
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  config/nginx.conf
Labels: Status: Review Needed

#263 fix: configurations _use_postgresql and _use_storage are ignored (#262)
  adm/_plugins.postinstall
  adm/_plugins.preuninstall
Labels: Status: Review Needed, backport-to-2.2

#267 test: add integration test on table creation
  integration_tests/0002_issue21/test.sh
  integration_tests/0004_create_table/test.sh
Labels: Status: Merge Now, backport-to-2.1, backport-to-2.2

#271 test: add integration test on table creation
  integration_tests/0004_create_table/foobar-0.0.1-1.metwork.mfbase.plugin
  integration_tests/0004_create_table/test.sh
Labels: Status: Merge Now, backport-to-2.2

#270 build: fix
  integration_tests/0004_create_table/foobar-0.0.1-1.metwork.mfbase.plugin
  integration_tests/0004_create_table/test.sh
Labels: Status: Review Needed, Status: Merge Now

#272 test: add integration test on table creation
  integration_tests/0004_create_table/foobar-0.0.1-1.metwork.mfbase.plugin
  integration_tests/0004_create_table/test.sh
Labels: Status: Merge Now

#264 fix: major issue with public schema (#252)
  adm/_create_plugin_database.sh
Labels: Status: Review Needed
